services:
  okta-ai-agent:
    build:
      context: .
    image: fctrid/ai-agent-for-okta:latest
    pull_policy: always  # Always pull the latest image
    container_name: okta-ai-agent
    ports:
      - "8001:8001"  # Expose HTTPS port
    volumes:
      # Database directories
      - ./sqlite_db:/app/sqlite_db      # SQLite database (auth, metadata)
      - ./graph_db:/app/graph_db        # Graph database (Okta business data)
      
      # SSL certificates for HTTPS
      - ./certs:/app/src/backend/certs
      
      # Application logs
      - ./logs:/app/logs
    env_file:
      - .env  # Use variables from .env file
    environment:
      # Database locations inside container
      - DB_DIR=/app/sqlite_db
      - DB_FILENAME=okta_sync.db
      - GRAPH_DB_PATH=/app/graph_db/okta_graph.db
      
      # CORS settings
      - ALLOWED_ORIGINS=https://localhost:*,https://127.0.0.1:*
    restart: unless-stopped  # Automatically restart container if it crashes
    networks:
      - okta-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G

networks:
  okta-network:
    driver: bridge