version: '3.8'

services:
  okta-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okta-ai-agent
    ports:
      - "8001:8001"  # Expose HTTPS port
    volumes:
      # Database directory - contains all SQLite data
      - ./sqlite_db:/app/sqlite_db
      
      # SSL certificates for HTTPS
      - ./certs:/app/src/backend/certs
      
      # Application logs
      - ./logs:/app/logs
    env_file:
      - .env  # Use variables from .env file
    environment:
      # Database location inside container
      - DB_DIR=/app/sqlite_db
      - DB_FILENAME=okta_sync.db
      
      # CORS settings
      - ALLOWED_ORIGINS=https://localhost:*,https://127.0.0.1:*
    restart: unless-stopped  # Automatically restart container if it crashes
    networks:
      - okta-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

networks:
  okta-network:
    driver: bridge