/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    ChatContainer: typeof import('./src/components/views/chatContainer.vue')['default']
    ChatInterfaceV2: typeof import('./src/components/ChatInterfaceV2.vue')['default']
    DataDisplay: typeof import('./src/components/messages/DataDisplay.vue')['default']
    DiscoveryPanel: typeof import('./src/components/messages/DiscoveryPanel.vue')['default']
    ExecutionPanel: typeof import('./src/components/messages/ExecutionPanel.vue')['default']
    HistorySidebar: typeof import('./src/components/layout/HistorySidebar.vue')['default']
    LoginView: typeof import('./src/components/views/LoginView.vue')['default']
    NotFoundView: typeof import('./src/components/views/NotFoundView.vue')['default']
    ReActThinkingSteps: typeof import('./src/components/messages/ReActThinkingSteps.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupView: typeof import('./src/components/views/SetupView.vue')['default']
    SyncStatusButton: typeof import('./src/components/sync/SyncStatusButton.vue')['default']
  }
}
